name = "ESM"
uuid = "31170fb7-9259-406e-89cb-fc418a8fef2f"
authors = ["Micha <micha_claydon@yahoo.co.uk>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FCSFiles = "d76558cf-badf-52d4-a17e-381ab0b0d937"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
PDFmerger = "3beb2ed1-af7d-458f-b727-6e9beb3586c0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RegularizationTools = "29dad682-9a27-4bc3-9c72-016788665182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
Aqua = "0.8.14"
CSV = "0.10.15"
Combinatorics = "1.0.3"
Comonicon = "1.0.8"
DataFrames = "1.8.1"
DataInterpolations = "8.8.0"
DataStructures = "0.19.3"
Dates = "1.10"
FCSFiles = "0.2.0"
FileIO = "1.17.1"
GLM = "1.9.0"
JSON = "0.21, 1"
KernelDensity = "0.6.10"
Meshes = "0.55.11"
NonlinearSolve = "4.12.0"
PDFmerger = "0.3.3"
Parameters = "0.12.3"
Pkg = "1.10"
Plots = "1.41.1"
Printf = "1.10.0"
ProgressMeter = "1.10"
RegularizationTools = "0.6.0"
SHA = "0.7.0, 1"
StableHashTraits = "2.0.2"
Statistics = "1.10"
StatsBase = "0.34.7"
StringEncodings = "0.3.7"
Test = "1.10"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"
XLSX = "0.10.4"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
StableHashTraits = "c5dd0088-6c3f-4803-b00e-f31a60c170fa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Aqua", "Pkg", "SHA", "Test", "TestItemRunner", "TestItems", "StableHashTraits"]
